### ISSUE TITLE
Compiles OK, Runs OK, but no map displayed on web

### ISSUE THREAD

**Issue by fstltna** [thomasrudin-mt/mapserver#26]
I have it set up properly, as best I can, but I see an issue where the website just shows a white screen. I see the server process running and getting incremental updates, but no web data. You can see this at http://hosting.gameplayer.club:8080...

Please help! If there is a better forum to ask for help let me know...

**Comment by thomasrudin** [comment]
Looks like #17 for me, which was fixed with: 8cc9a67215624a071e7057566b3f02873faa9de6

Can you compile it yourself and try it with the latest `master` branch?
If not, tell me, i will build a release with the current features..

**Comment by fstltna** [comment]
I tried building from the github but I get a error about build-all-docker failing. Can your create a binary for me? I'm on Ubuntu 16.04...

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by thomasrudin** [comment]
Bugfix Release 1.0.2:
https://github.com/thomasrudin-mt/mapserver/releases/tag/1.0.2

**Comment by fstltna** [comment]
That file is still 1.0.1...

Marisa 

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by fstltna** [comment]
I managed to build it myself, but seems you didn't bump the version number inside😄 however I am still having the issue. In the shell that's running mapserver i see it doing the incremental updates but the map stays blank 😥

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by fstltna** [comment]
I got it working 😄 had to delete the map maker data files and recreate them from scratch. Web page now working fine. Thanks again!

Marisa

----
https://synchronetbbs.org/OurServers - all the servers I am responsible for

**Comment by thomasrudin** [comment]
I just saw :smile: the version thing is a mistake on my part: i forgot to manually bump it :P
If you have other issues, feel free to post them here...

just fyi: i think the other layers don't work properly yet...
